name: build-test

on:
  workflow_call:
    inputs:
      java-version:
        description: "Java version"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: SetUp Java ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: ${{ inputs.java-version }}

      - name: Building Packages
        run: |
          mvn clean install
          echo "Completed Build"

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: use Java ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: ${{ inputs.java-version }}

      - name: Testing the packages
        run: mvn test
